### ISSUE TITLE
GDTF import fail - Base, Yoke, Head, Beam geometry naming is required

### ISSUE THREAD

**Issue by rudolfsbaltins** [open-stage/blender-dmx#17]
Hi, had an import fail for a GDTF file - https://gdtf-share.com/user-page?name=JB-Lighting&page=fixtures

Python: Traceback (most recent call last):
  File "C:\Users\r\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dmx\panels\fixtures.py", line 243, in execute
    dmx.addFixture([self.name](http://self.name/)+" "+str(i+1), self.profile, self.universe, self.address, self.mode, self.gel_color)
  File "C:\Users\r\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dmx\__init__.py", line 501, in addFixture
    dmx.fixtures[-1].build(name, profile, mode, universe, address, gel_color)
  File "C:\Users\r\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dmx\fixture.py", line 149, in build
    model_collection = DMX_Model.getFixtureModelCollection(gdtf_profile)
  File "C:\Users\r\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dmx\model.py", line 35, in getFixtureModelCollection
    return DMX_GDTF.buildCollection(profile)
  File "C:\Users\r\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dmx\gdtf.py", line 217, in buildCollection
    updateGeom(profile)
  File "C:\Users\r\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dmx\gdtf.py", line 215, in updateGeom
    updateGeom(child_geom, d+1)
  File "C:\Users\r\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dmx\gdtf.py", line 179, in updateGeom
    obj_child = objs[[geom.name](http://geom.name/)]
KeyError: 'Base'

**Comment by hugoaboud** [comment]
Hi rudolf,

This problem occurs because the plugin is expecting the fixture to have a "Base" object, which is not a good decision.
I have flagged it as a bug and will work on it after we merge some new features and fixes that @vanous is working on.

Thanks for the report

**Comment by rudolfsbaltins** [comment]
When do you see this coming? I am working on a DMX workflow as I do stage
design and it looks like it might be moving in the direction of light
design.
You don't have any future plans on MVR scene support?

**Comment by vanous** [comment]
Fixing the dependency on naming will take some time, but you can work around right now by editing the GDTF file in the GDTF Builder and renaming the base, yoke, head to Base, Yoke, Head.

As for MVR, do you have an example file that you could post here?

Thank you
