### ISSUE TITLE
Error after some using.

### ISSUE THREAD

**Issue by FreSS13** [open-stage/blender-dmx#61]
Greetings, i have some issue, first time i found it at first installing of  add on. 
I reinstall blender (full, with deleting all user data) and it helps for short period of time, but then i have a same issue repot in console.
It happens when i try to add  any fixture in my project.
I think it can be a conflict with other addons but it's not simply to understand with each, beacase after re install an turning on another addons, dmx addon works, and i can't cath a moment after which it stands broken.

`Python: Traceback (most recent call last):
  File "C:\Users\Михаил\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dmx\panels\fixtures.py", line 266, in execute
    dmx.addFixture(self.name+" "+str(i+1), self.profile, self.universe, self.address, self.mode, self.gel_color, self.display_beams)
  File "C:\Users\Михаил\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dmx\__init__.py", line 683, in addFixture
    dmx.fixtures[-1].build(name, profile, mode, universe, address, gel_color, display_beams, position, focus_point)
  File "C:\Users\Михаил\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dmx\fixture.py", line 275, in build
    emitter_material = getEmitterMaterial(obj.name)
  File "C:\Users\Михаил\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dmx\material.py", line 41, in getEmitterMaterial
    material.node_tree.links.new(material.node_tree.nodes[MATERIAL_OUTPUT].inputs[0], material.node_tree.nodes[EMISSION].outputs[0])
KeyError: 'bpy_prop_collection[key]: key "Излучение" not found'
`

**Comment by vanous** [comment]
Hello. The issue is in Blender being set to Russian. This should be fixed in next release. I think that the next release will be soon.

**Comment by FreSS13** [comment]
Yes, it's a reason thanks, i use ToolTips on russian

**Comment by vanous** [comment]
I just released 1.0.2, this should solve the issue... 🤞
